#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# /app/config/routes.yaml
#captcha_routing:
# resource: "@CaptchaBundle/Resources/config/routing.yml"
# config/routes.yaml
security_logout:
  path: '/logout'
  methods: ['GET'] # You can use POST if preferred
